version: "3.3"

services:
  db:
    image: postgres:alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gitlabdumptables
      - POSTGRES_USER=read_user
      - POSTGRES_PASSWORD=read_password
      - POSTGRES_HOST=localhost
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=gitlabdumptables
      - POSTGRES_USER=read_user
      - POSTGRES_PASSWORD=read_password
    depends_on:
      - db