# Generated by Django 4.0.6 on 2022-09-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackApp', '0003_exportsamedateissues'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daytotaluser',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('spent', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('date_spent', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daytotaluser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Issueperdayuser',
            fields=[
                ('project', models.CharField(blank=True, max_length=255, null=True)),
                ('projectid', models.IntegerField(blank=True, null=True)),
                ('issue', models.CharField(blank=True, max_length=255, null=True)),
                ('issueid', models.IntegerField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('spent', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('date_spent', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'issueperdayuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Issuetotaluser',
            fields=[
                ('issue', models.CharField(blank=True, max_length=255, null=True)),
                ('issueid', models.IntegerField(primary_key=True, serialize=False)),
                ('project', models.CharField(blank=True, max_length=255, null=True)),
                ('projectid', models.IntegerField(blank=True, null=True)),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('spent', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'issuetotaluser',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Exportsamedateissues',
        ),
    ]
